spring.application.name=hulysses-one
spring.datasource.url=jdbc:postgresql://localhost:5432/hulysses_one
spring.datasource.username=postgres
spring.datasource.password=proghuly

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false