spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:classpath:/config-repo/}
          add-label-locations: false
        accept-empty: false
server:
  port: ${CONFIG_SERVER_PORT:8888}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
